spring:
  application:
    name: ms-event-management
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONG_PORT:27017}
      database: ${MONGO_DATABASE:db_event}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: ${MONGO_AUTH_DB:admin}