spring:
  application:
    name: ms-ticket-management
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONG_PORT:27017}
      database: ${MONGO_DATABASE:db_ticket}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: ${MONGO_AUTH_DB:admin}
  rabbitmq:
    queue: ticket-queue
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

springdoc:
  packages-to-scan: br.com.compass.ticketmanagement.controllers
  swagger-ui:
    path: /ticketmanagement.html
  api-docs:
    path: /ticketmanagement

feign:
  event:
    url: ${EVENT_URL:localhost:8080}

server:
  port: 8081